dist: trusty
language: rust
cache: cargo
matrix:
  include:
    - env: TARGET=armv5te-unknown-linux-musleabi CARGO_TARGET_ARMV5TE_UNKNOWN_LINUX_MUSLEABI_LINKER=arm-linux-musleabihf-gcc CC_armv5te_unknown_linux_musleabi=arm-linux-musleabihf-gcc CXX_armv5te_unknown_linux_musleabi=arm-linux-musleabihf-g++
    - env: TARGET=x86_64-unknown-linux-musl
      secure: "lDiSQneQx8u/BIPFCaUfdkmO+KeNjxA71v4mFJ9WDgzDUh0uZSxotkoZZ8mwJMsF22kgfAqaBw0xHoA1Z4mBSuVlVbUBvOJB46VZp3x0o8qb4YOnvx+utx6eYm5SLz0a/JWUSNfvyghXQ7tp/ybE5ejkMlH6ucKh/axmCMjTC/4//AeBPC8klU8ZHVUUS4mbIoThCLAOrjGoYxBcCzQiB7lAzt6KOOumi3LVaxXDCMbeKmRWtG2RV5XzWfl/IXSqbN5U7NyqtCgumOreHmD8A6Aws04M0xghU6njOH6mFPeSC6k6zDggnjkrs2MBKSLVs5UKfjBcBwvMyAtoF5ZwKLLLhpiT1rzT3bgcMw8uDUSK78zP85VvjY2vKRZXkAVzNOzW7/zaKMWY7Hp1OzyNe/4646bUmHFjwaPK9ceeMOW0bRnMDrzrI914CLPkt5ZBEskFxI2oFTrojH3/oIkrSGgjqlfIlu2zjvGvmAblzGPrmp7sVvqpcaMdpR3kgRbr0gg7ng7mFu04lJPevWyMqsf0H1xp8tzPHv/HvKx6AhCfOdMy+ADayLBeVHatjrLBmm6WXFxAVFHurWHeckT4vvhGhsaFWy3JWWoCn5bQ57Vcv1v36c9c9zMZJ40pgAVRDpAO1X7IvBv1d41/zRvXeX/fJ+QmNinzNqbOV1DR84Q="
      secure: "pusowYza9jhuBPY3YGQoUoDPTvyH1g71obk4+ZtklrRECjhZXC/scx/swRsQnb37WkbmWQJp70KCqTnkbPif1QUaXqD1ksna4T9YxDen2kwS2HRwkU+PuglQfop2HaDsOW0BKICyFcslWPOucS0HRaFlPWxj3AAoOeVXIaR2OZcOufj9k8xDMIXzfI+Zx6CFs9k7mhH/DJQw4T5/fbxP+nHycHXOSxCzWMLqJ97bV8vlS+lUdhtxPzEJ3zy4fJ2Sk7NJdfKnfRBeIvvjysp3rxI203WDhiUZJDhs2//opp/tuo2XLpPtcZj8BnMk1HYciA/JqmF3ESR03+WgfG32wtPF6PMUzfhYr58OGXKXQKBUYCHY1fRuLxE+C1e/qpUN5d8oogWySa2Xsih81WE4cL7NKLUObnpygUJxWcil3pp1Ys79FZmM2ljBq8fWQFu4XOnUMsa8Vewh/pW3cF/G1nyE5aak0p/sMOcFaUgtXwIr97EEiDW9OPYtYAnWbqKhRYRtdTkFT2MH2ysGrBo6YqGQbVx4gZkMzt7QcGrUMHHVKH11GUjH6mV1np3egVuesiG3aPIjUb5m/zqUH+k58R8Q+kBF0au1YXJM/xQTRRhtgNHIfNSNRDAR2h2opaKzEU2vQjFME/wUwXcFALH9RxabttpjqPt7dAS9iWamzfU="
      addons:
        apt:
          packages:
            - musl-tools
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-pc-windows-msvc
      os: windows

script:
  - sh ci/build.sh

deploy:
  - provider: releases
    api_key:
      secure: "p9JvbtkiqTWzpINHyvAQi6cllq3bfuday2BSgN5J+dJ5XAOhwkSA0DDg0eTaOWFyF6QrIpaPq3AGRG2GAv5niIozGK8P5KkEVMEsBZEAzUjTA1i26lL3zFi5fKImf4Ez3yXUZYefm14yshkZ57TpT/NdP8bbhueRj/QxO1Bo5Ah+cbvdfI4tef9hLc9VnyGBWjHaL042xBUaGmE3Xtq1g2r97QrJeWkaK0XlJYR1/QAzVDw3IXpT2/Y1mrkiw36eanvPRtG1vaf2+Kz08q/gBYnLTwnEu+sFinLtdlXPVOO6I44+qtwlHqcw5RPyxcZctK8gAudO07CYT7IuLpOY+wPC9aLVMNdb9dtJZZMFcj/5f5YEi+zgzcROeTq5rvY+sTZTZgywBpMVHnEE0nCnXuFkvqsFgPEA/W9lKzNYYAfwn7rnwOsqsexZ+83uEF2jmIHhNccp2eBPBdkCVol/y9voc81BmNxD/kXS8a+/iGu69TZ52fhTJMYtV+dLNRurYI+/O7jMeS7pibp2/o9JlFSIU50rnW2LFzvKPLugAWXiJZr3n+SspB9405VXdNchnL4P5gJDN3v3ta+Gl/2rQi1TZXkseWKywjm5/cXK7b5GT0fcbdhZN/B1KWSv9PVxhNEzTQCb8tBR/euOx5l830UROJDDugs9CwnLO4tCC5k="
    file: rsnova-$TRAVIS_TAG-$TARGET.tar.gz
    on:
      tags: true
      repo: yinqiwen/rsnova
    skip_cleanup: true
    overwrite: true
  - provider: script
    script: bash ./Docker/docker_push.sh
    skip_cleanup: true
    on:
      tags: true
      condition: $TARGET = x86_64-unknown-linux-musl