dist: trusty
language: rust
cache: cargo
matrix:
  include:
    - env: TARGET=armv5te-unknown-linux-musleabi CARGO_TARGET_ARMV5TE_UNKNOWN_LINUX_MUSLEABI_LINKER=arm-linux-musleabihf-gcc
    - env: TARGET=x86_64-unknown-linux-musl
      addons:
        apt:
          packages:
            - musl-tools
    - env: TARGET=x86_64-apple-darwin
      os: osx

script:
  - sh ci/build.sh

deploy:
  api_key:
    secure: "YngDT2JlydCG+qb8Ww9wBFyWiLRQJczybNLeoFKluBXKoh1Vu+TZeReMK+rRUjOqOmYV8sNtOnEVSg4+ICeYDNp9fRRwcNKTkp0H+8pH0OynxdH2faCjx1H5U0WQuWqMLQoMSHZ90I0tL40kEJOChLY6WGvwY47YBqi/dsvmTfg="
  file: rsnova-$TRAVIS_TAG-$TARGET.tar.gz
  on:
    tags: true
  provider: releases
  skip_cleanup: true
  overwrite: true