#cargo-features = ["edition"]
#edition = "2018"

[package]
name = "rsnova"
version = "0.1.0"
authors = ["yinqiwen <yinqiwen@gmail.com>"]
edition = "2018"

[features]

[dependencies]
clap = "~2.33"
log = "0.4"
flexi_logger = "0.14"
#simplelog = "^0.6.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.4"
#tokio = "=0.2.0-alpha.1"
tokio = { version = "0.2.0",  features = ["full"] }
tokio-io-timeout = "0.3.1"
#tokio-sync="0.1"
#tokio-sync="0.1"
bytes = "0.5"
futures = "0.3"
#futures-preview = "=0.3.0-alpha.17"
httparse = "1.0"
byteorder = "1"
nom = "^4.2"
bincode = "1.1"
lazy_static = "1.3.0"
url = "1.7"
rand = "0.6"
skip32 = "1.0"
nix = "0.14.1"
cfg-if = "0.1"
twoway = "0.2"
unicase = "2.4"
#trust-dns = "0.16"
ring = "0.14"
crc = "^1.0.0"
regex = "1"
#lz4-compress="0.1"



