cargo-features = ["edition"]
edition = "2018"

[package]
name = "rsnova"
version = "0.1.0"
authors = ["yinqiwen <yinqiwen@gmail.com>"]

[features]

[dependencies]
clap = "~2.33"
log = "0.4"
simplelog = "^0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-io = "0.1"
tokio = "0.1"
tokio-udp="0.1"
tokio-io-timeout = "0.3.1"
tokio-sync="0.1"
bytes = "0.4.12"
futures = "0.1"
httparse = "1.0"
tls-parser = "0.7.0"
byteorder = "1"
nom = "^4.2"
bincode = "1.1"
lazy_static = "1.3.0"
url = "1.7"
rand = "0.6"
skip32 = "1.0"
orion ="0.14"
nix = "0.14.1"
cfg-if = "0.1"
actix-http = "0.2"
twoway = "0.2"
unicase = "2.4"

