[log]
logtostderr = true
level = "info"
logdir = "./"

[common]

[[tunnel]]
listen = "rmux://127.0.0.1:48101"
pac=[{host = ".*", channel = "direct"}]
cipher = {key="abcdefg", method = "chacha20poly1305"}
